image: devcurmudgeon/foo

before_script:
- sh ./install.sh

variables:
  NO_BUILD: "True"
  BASE: "/src"

cache:
  path: "$BASE"

stages:
- pep8
- installation
- cache_keys
- build
- test
- deploy

check_pep8:
  stage: pep8
  script: "pep8"

check_installation:
  stage: installation
  script: "python setup.py install ; ./ybd.py"

check_cache_keys:
  stage: cache_keys
  script: "echo 'mode: keys-only' > ./ybd.conf && ../ybd/ybd.py ci x86_64"
