language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
script:
  - pip install fs pyyaml sandboxlib requests jsonschema
  - chmod +x ybd.py
  - ybd.py ci x86_64
